version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm ci || npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm ci || npm install
      # Run optional required steps before releasing
      # - run: npm run build-script
      - run: npx semantic-release


workflows:
  version: 2
  build_and_release:
    jobs:
      build:
        filters:
          branches:
            only:
              - master
              - dev
              - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    release:
      filters:
        branches:
          only:
            - master
            - dev
            - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
